version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: productsdb
      POSTGRES_USER: sail
      POSTGRES_PASSWORD: pass
    ports:
      - "5436:5432"
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/productsdb
#      SPRING_DATASOURCE_USERNAME: sail
#      SPRING_DATASOURCE_PASSWORD: pass
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#      SPRING_JPA_SHOW_SQL: "true"
#      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
